### ISSUE TITLE
I don't understand how to add dependency (new to all this)

### ISSUE THREAD

**Issue by iherbivore** [LuxDie/angular2-seed-jade#5]
This seed seems like a good starting point. I am trying to add the [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap) Mostly things seem to be working out. 
First I installed it:
`npm i ng2-bootstrap --save`

From there I entered the realm of guessing at stuff. I found seemingly relevant entries in the config.ts and added the ng2-bootstrap in the dev and production area. Is this the right thing to do?
` 
export const DEV_NPM_DEPENDENCIES: IDependency[] = normalizeDependencies([
  { src: 'systemjs/dist/system-polyfills.src.js', inject: 'shims' },
  { src: 'reflect-metadata/Reflect.js', inject: 'shims' },
  { src: 'es6-shim/es6-shim.js', inject: 'shims' },
  { src: 'systemjs/dist/system.src.js', inject: 'shims' },
  { src: 'angular2/es6/dev/src/testing/shims_for_IE.js', inject: 'shims' },
  { src: 'angular2/bundles/angular2-polyfills.js', inject: 'shims' },
  { src: 'rxjs/bundles/Rx.js', inject: 'libs' },
  { src: 'angular2/bundles/angular2.js', inject: 'libs' },
  { src: 'angular2/bundles/router.js', inject: 'libs' },
  { src: 'angular2/bundles/http.js', inject: 'libs' },
  { src: 'ng2-bootstrap/bundles/ng2-bootstrap.js', inject: 'libs' },
  { src: 'bootstrap/dist/css/bootstrap.css', inject: true }
]);
`
`
export const PROD_NPM_DEPENDENCIES: IDependency[] = normalizeDependencies([
  { src: 'systemjs/dist/system-polyfills.src.js', inject: 'shims' },
  { src: 'reflect-metadata/Reflect.js', inject: 'shims' },
  { src: 'es6-shim/es6-shim.min.js', inject: 'shims' },
  { src: 'angular2/es6/dev/src/testing/shims_for_IE.js', inject: 'shims' },
  { src: 'systemjs/dist/system.js', inject: 'shims' },
  { src: 'angular2/bundles/angular2-polyfills.min.js', inject: 'libs' },
  { src: 'ng2-bootstrap/bundles/ng2-bootstrap.min.js', inject: 'libs' },
  { src: 'bootstrap/dist/css/bootstrap.min.css', inject: true }
]);
`

ng2-bootstrap says it needs moment like this:
`typings install moment --save`

The part I seem to get stuck on is where it says it needs this entry:
` System.config({
    packages: {
      app: {
        format: 'register',
        defaultExtension: 'js'
      }
    },
    map: {
      moment: 'node_modules/moment/moment.js'
    }
  });`

I don't quite understand how to do that. It doesn't quite seem to fit the other things in the config.ts. 
 When I try to run I get a 404 error for http://localhost:5555/node_modules/moment.js

The node_modules/moment/moment.js exists, but it is missing the /moment/ folder when looking for it.

Thanks!

**Comment by iherbivore** [comment]
Huzzah! I figured it out. The following change got it working:
`const SYSTEM_CONFIG_DEV = {
  defaultJSExtensions: true,
  paths: {
    [BOOTSTRAP_MODULE]: `${APP_BASE}${BOOTSTRAP_MODULE}`,
    'angular2/*': `${APP_BASE}angular2/*`,
    'rxjs/*': `${APP_BASE}rxjs/*`,
    '*': `${APP_BASE}node_modules/*`
  },
  packages: {
    angular2: { defaultExtension: false },
    rxjs: { defaultExtension: false }
  },
  map: {
    moment: 'moment/moment.js'
  }
};`

**Comment by LuxDie** [comment]
I'm glad you worked it out.

I took the liberty of improving the formatting of your snippets, to store for future reference.
